# Generated by Django 3.2.7 on 2021-10-23 03:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contactar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('correo', models.EmailField(default=None, max_length=254)),
                ('lugar', models.CharField(max_length=90)),
                ('interes', models.TextField(default=None, max_length=90)),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('nombre', models.CharField(default=None, max_length=100)),
                ('identificacion', models.IntegerField(default=None, primary_key=True, serialize=False)),
                ('correo', models.EmailField(default=None, max_length=254)),
                ('edad', models.IntegerField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='Programar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default=None, max_length=100, null=True)),
                ('edad', models.IntegerField(default=None, null=True)),
                ('lugar', models.CharField(max_length=90, null=True)),
                ('correo', models.EmailField(default=None, max_length=254, null=True)),
                ('fecha_inicio', models.DateField(null=True)),
                ('n_personas', models.IntegerField(null=True)),
                ('dias', models.IntegerField(null=True)),
                ('nota', models.TextField(default=None, null=True)),
                ('identificacion', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Suscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correo', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('persona', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='aplicacion.persona')),
            ],
        ),
    ]
