# Generated by Django 3.2.7 on 2021-10-23 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programar',
            name='correo',
            field=models.EmailField(default=None, max_length=254),
        ),
        migrations.AlterField(
            model_name='programar',
            name='edad',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='programar',
            name='nombre',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
