# Generated by Django 3.2.7 on 2021-10-23 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0002_auto_20211022_2300'),
    ]

    operations = [
        migrations.AddField(
            model_name='programar',
            name='presupuesto',
            field=models.IntegerField(null=True),
        ),
    ]
