# Generated by Django 3.2.7 on 2021-10-24 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0003_programar_presupuesto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='programar',
            old_name='lugar',
            new_name='destino',
        ),
    ]
