# Generated by Django 3.2.7 on 2021-10-24 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0004_rename_lugar_programar_destino'),
    ]

    operations = [
        migrations.RenameField(
            model_name='programar',
            old_name='fecha_inicio',
            new_name='fecha',
        ),
    ]
