# Generated by Django 3.2.7 on 2021-10-24 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0005_rename_fecha_inicio_programar_fecha'),
    ]

    operations = [
        migrations.RenameField(
            model_name='programar',
            old_name='n_personas',
            new_name='personas',
        ),
    ]
