# Generated by Django 3.2.7 on 2021-10-24 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0007_rename_nota_programar_comentario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programar',
            name='fecha',
            field=models.DateTimeField(null=True),
        ),
    ]
