# Generated by Django 3.2.7 on 2021-10-27 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0009_auto_20211026_2126'),
    ]

    operations = [
        migrations.RenameField(
            model_name='persona',
            old_name='edad',
            new_name='telefono',
        ),
    ]
