# Generated by Django 3.2.7 on 2021-10-29 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0011_auto_20211029_1319'),
    ]

    operations = [
        migrations.CreateModel(
            name='Planear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default=None, max_length=100, null=True)),
                ('destino', models.CharField(max_length=90, null=True)),
                ('correo', models.EmailField(default=None, max_length=254, null=True)),
                ('comentario', models.TextField(default=None, null=True)),
            ],
        ),
    ]
