# Generated by Django 3.2.7 on 2021-10-30 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0013_alter_suscripcion_correo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Suscripcion',
        ),
    ]
