# Generated by Django 3.2.7 on 2021-10-31 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0015_auto_20211031_1316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programar',
            name='dias',
        ),
        migrations.RemoveField(
            model_name='programar',
            name='identificacion',
        ),
        migrations.AddField(
            model_name='programar',
            name='nombre',
            field=models.CharField(max_length=90, null=True),
        ),
    ]
