# Generated by Django 3.2.7 on 2021-10-31 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0016_auto_20211031_1323'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programar',
            name='creacion',
        ),
        migrations.RemoveField(
            model_name='programar',
            name='modificacion',
        ),
        migrations.AddField(
            model_name='programar',
            name='dias',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='programar',
            name='identificacion',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='programar',
            name='personas',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='programar',
            name='nombre',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
